### ISSUE TITLE
emm....收益率=ln(close_price/open_price).....ln是自然对数函数?

### ISSUE THREAD

**Issue by mikawudi** [TsingJyujing/tushare-joining-test#1]
如题,没有看懂为啥要用ln函数的说....能解释下么谢谢

**Comment by gaoquanao** [comment]
https://www.zhihu.com/question/30113132

**Comment by TsingJyujing** [comment]
楼上说的很好了，其实这个是计算波动率的时候使用的收益率，所以用对数收益率，至于为什么，知乎上也有，可以搜一下。

**Comment by mikawudi** [comment]
好的~谢谢两位解惑撒~撸个spider进群撒~
